require 'colorize'
task default: :instrustions
USER = `whoami`.strip
CURRENT_DIR = `basename $(pwd)`.strip

task :install do
  sh "bundle install"
end

task :lint do
  sh "bundle exec rubocop -a"
end

task :instrustions do
  puts <<~HEREDOC

    Hi #{USER.green}! Welcome to #{CURRENT_DIR.red} #{"POWERED BY RAKE".yellow}

    Getting started

    rake install                  Install dependencies
    rake lint                     Run linter
  HEREDOC
end
